"""add phase2 lecture notes columns

Revision ID: 374c72daeb02
Revises: 
Create Date: 2026-05-02 08:45:12.030032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '374c72daeb02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('youtube_id', sa.String(length=20), nullable=True))
    op.add_column('lectures', sa.Column('transcript_raw', sa.Text(), nullable=True))
    op.add_column('lectures', sa.Column('transcript_source', sa.String(length=20), nullable=True))
    op.add_column('lectures', sa.Column('transcript_quality', sa.String(length=10), nullable=True))
    op.add_column('lectures', sa.Column('notes_md', sa.Text(), nullable=True))
    op.add_column('lectures', sa.Column('notes_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lectures', sa.Column('notes_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lectures', 'notes_status')
    op.drop_column('lectures', 'notes_generated_at')
    op.drop_column('lectures', 'notes_md')
    op.drop_column('lectures', 'transcript_quality')
    op.drop_column('lectures', 'transcript_source')
    op.drop_column('lectures', 'transcript_raw')
    op.drop_column('lectures', 'youtube_id')
    # ### end Alembic commands ###
